<x-app-layout>
    @php($profile = auth()->user()->registrationProfile)
    @php($isVolunteer = auth()->user()->account_type === 'volunteer')
    <div class="mx-auto max-w-7xl px-4 py-8 sm:px-6 sm:py-12 lg:px-8">
        <section class="relative overflow-hidden rounded-3xl bg-[#31421e] px-6 py-9 text-white shadow-xl sm:px-10 lg:px-12 lg:py-12">
            <div class="relative z-10 max-w-2xl"><span class="inline-flex rounded-full bg-white/10 px-4 py-2 text-xs font-bold text-[#dfe6d5]">{{ $isVolunteer ? 'حساب متطوع' : 'حساب كبير سن' }}</span><h1 class="mt-5 text-3xl font-black sm:text-4xl">مرحبًا، {{ auth()->user()->name }}</h1><p class="mt-3 leading-8 text-[#dfe6d5]">{{ $isVolunteer ? 'شكرًا لانضمامك إلى مجتمع العطاء. ملفك جاهز للمرحلة التالية من تقديم الخدمات.' : 'أهلًا بك في إحسان. يمكنك إدارة بياناتك ومتابعة حسابك بسهولة من هنا.' }}</p><a href="{{ route('profile.edit') }}" class="mt-7 inline-flex rounded-xl bg-white px-6 py-3 font-bold text-[#31421e] hover:bg-[#eef2e8]">تعديل الملف الشخصي</a></div>
            <div class="absolute -bottom-20 -left-16 hidden h-72 w-72 rounded-full bg-[#718256]/40 lg:block"></div>
        </section>

        <div class="mt-7 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
            <article class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p class="text-sm font-bold text-slate-400">حالة الحساب</p><div class="mt-3 flex items-center gap-3"><span class="h-3 w-3 rounded-full bg-emerald-500"></span><span class="text-xl font-extrabold text-[#31421e]">مسجّل بنجاح</span></div></article>
            <article class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p class="text-sm font-bold text-slate-400">نوع الحساب</p><p class="mt-3 text-xl font-extrabold text-[#31421e]">{{ $isVolunteer ? 'متطوع' : 'كبير سن' }}</p></article>
            <article class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:col-span-2 lg:col-span-1"><p class="text-sm font-bold text-slate-400">تاريخ الانضمام</p><p class="mt-3 text-xl font-extrabold text-[#31421e]">{{ auth()->user()->created_at->translatedFormat('d M Y') }}</p></article>
        </div>

        <div class="mt-7 grid gap-7 lg:grid-cols-[1.35fr_.65fr]">
            <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><div class="flex items-center justify-between gap-4"><div><p class="text-sm font-bold text-[#718256]">نظرة عامة</p><h2 class="mt-1 text-2xl font-black text-[#31421e]">بيانات الحساب</h2></div><a href="{{ route('profile.edit') }}" class="text-sm font-bold text-[#52643a] hover:underline">تعديل</a></div><dl class="mt-7 grid gap-5 sm:grid-cols-2"><div class="rounded-xl bg-slate-50 p-4"><dt class="text-xs font-bold text-slate-400">البريد الإلكتروني</dt><dd class="mt-1 break-all font-bold">{{ auth()->user()->email }}</dd></div><div class="rounded-xl bg-slate-50 p-4"><dt class="text-xs font-bold text-slate-400">رقم الجوال</dt><dd class="mt-1 font-bold">{{ $profile?->phone ?? 'غير مضاف' }}</dd></div>@if($isVolunteer)<div class="rounded-xl bg-slate-50 p-4 sm:col-span-2"><dt class="text-xs font-bold text-slate-400">رقم الهوية</dt><dd class="mt-1 font-bold">{{ $profile?->identity_number ?? 'غير مضاف' }}</dd></div>@else<div class="rounded-xl bg-slate-50 p-4"><dt class="text-xs font-bold text-slate-400">المدينة</dt><dd class="mt-1 font-bold">{{ $profile?->city ?? 'غير مضافة' }}</dd></div><div class="rounded-xl bg-slate-50 p-4"><dt class="text-xs font-bold text-slate-400">نوع السكن</dt><dd class="mt-1 font-bold">{{ ['apartment'=>'شقة','house'=>'منزل مستقل','family'=>'سكن مع العائلة'][$profile?->housing_type] ?? 'غير مضاف' }}</dd></div>@endif</dl></section>
            <aside class="rounded-2xl bg-[#eef2e8] p-6 sm:p-8"><p class="text-sm font-bold text-[#718256]">الخطوة القادمة</p><h2 class="mt-2 text-2xl font-black text-[#31421e]">{{ $isVolunteer ? 'استعد لتقديم العون' : 'الخدمات ستصل إليك قريبًا' }}</h2><p class="mt-3 text-sm leading-7 text-slate-600">{{ $isVolunteer ? 'ستظهر هنا فرص التطوع والطلبات المناسبة عند تفعيل نظام الخدمات.' : 'ستتمكن من إنشاء طلب خدمة ومتابعته عند إطلاق المرحلة القادمة.' }}</p><div class="mt-6 rounded-xl border border-[#cdd9bd] bg-white/70 p-4 text-sm font-bold text-[#52643a]">هذه الوظيفة ضمن السبرنت القادم</div></aside>
        </div>
    </div>
</x-app-layout>
