services:
  - type: web
    name: ihsan-backend
    runtime: docker
    plan: free
    region: frankfurt
    branch: main
    autoDeployTrigger: commit
    healthCheckPath: /up
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: APP_NAME
        value: إحسان
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        sync: false
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: warning
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        fromDatabase:
          name: ihsan-db
          property: connectionString
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: sync
      - key: FILESYSTEM_DISK
        value: public

databases:
  - name: ihsan-db
    plan: free
    region: frankfurt
    databaseName: ihsan
    user: ihsan
